### HELPER FUNCTIONS FOR FGSEA RESULT DISPLAY ###
#################################################

#' Get a ranked vector of gene IDs
#'
#' @param lfc_dt data.table with at least "ENTREZID" and the respective statistics
#' by which the genes should be ranked (\code{rank_by}, e.g. "t" or "logFC"). This
#' should contain all genes of interest, e.g. those detectable expression
#' across all samples.
#' @param rank_by indicate the stat that you want to rank the genes by. Default: "t"
#' (must be part of \code{lfc_dt})
#'
#' @return vector of values of \code{rank_by}, sorted in decreasing order (from
#' highest to lowest) and named with ENTREZ IDs
#'
#' @export
#'
get_ranks <- function(lfc_dt = gns.2controls[[1]], rank_by = "t"){
  check_columns(c("ENTREZID", rank_by), lfc_dt, "lfc_dt", "run_fgsea_per_day")

  ## define the named vector of ranks
  rnks <- tibble::deframe( x = data.frame( lfc_dt[!is.na(ENTREZID),
                                                  mean(get(rank_by)),
                                                  by = "ENTREZID"]) )
  rnks <- sort(rnks, decreasing = TRUE)
  return(rnks)

}


#' Extract the top enriched pathways following fgsea
#'
#' @param fgsea_result object generated by \code{fgsea::fgsea}
#' @param n_pw integer indicating the number of top PWs to be returned; default: 5
#' @param direction either one of "up","down","either","both"
#' @param p_adj_threshold default: 0.01
#'
#' @return name(s) of pathways
#'
#' @examples \dontrun{
#' topPWs <- extract_top_pw(fg_reactome[[1]], n_pw = 5, direction = "both", p_adj_threshold = 0.01)
#' fgsea::plotGseaTable(pwi[topPWs], stats =  rank.l[[5]], fgseaRes = fg_reactome[[5]],  gseaParam = 0.5)
#' }
#'
#' @export
#'
extract_top_pw <- function(fgsea_result = fg_reactome[[i]],
                           n_pw = 5,
                           direction = c("up","down","either","both"),
                           p_adj_threshold = 0.01){

  check_columns(c("padj", "pval","pathway","ES"), input = fgsea_result,
                              "fgsea_result", "extract_top_pw")

  ## filter based on adj. p-value
  fgsea_result <- fgsea_result[padj < p_adj_threshold]

  ## sort based on p-value
  if(direction == "up"){
    tPW <- fgsea_result[ES > 0][head(order(pval), n=n_pw), pathway]
  }else if(direction == "down"){
    tPW <- rev(fgsea_result[ES < 0][head(order(pval), n=n_pw), pathway])
  }else if(direction == "either"){
    tPW <- fgsea_result[head(order(pval), n=n_pw), pathway]
  }else if(direction == "both"){
    tPW <- c(
      fgsea_result[ES > 0][head(order(pval), n=n_pw), pathway],
      rev(fgsea_result[ES < 0][head(order(pval), n=n_pw), pathway])
    )
  }

  return(tPW)

  }


#' Plot enrichment plot for top enriched pathway
#'
#' @description Pathway is selected based on ES and p-value order. Only one plot
#' at a time will be returned.
#'
#' @details Wrapper function around \code{\link{fgsea::plotEnrichment}} and
#' \code{\link{extract_top_pw}}.
#'
#' @param fgsea_result the object produced by \code{\link{fgsea::fgsea}}
#' @param title any string
#' @param original_pws the pathway-containing object that was used to generate
#' the fGSEA results to begin with
#' @param direction either "up" or "down"
#' @param ranked_vector the vector used with \code{fgsea} to generate the results
#'
#' @export
plot_top_pathway <- function(fgsea_result = fg_reactome[[i]], title = "Top PW",
                             orginal_pws = pw_reactome,
                             direction = "up",
                             ranked_vector){

  tPW <- extract_top_pw(fgsea_result, n_pw = 1, direction = direction)

  if(is.null(tPW)){stop("No gene sets met your criteria")
  }else{
    P <- fgsea::plotEnrichment(pathway = orginal_pws[[tPW]],
                        ranked_vector)
    P <- P + ggtitle(title, subtitle = paste(tPW, "(", direction, ")" ))
    return(P)
  }
}
